"""
Policy analysis and intervention modeling.

This module provides tools for analyzing critical points from topological
analysis and their socioeconomic interpretations.
"""

from poverty_tda.analysis.barriers import (
    BarrierImpact,
    BarrierProperties,
    analyze_barrier_impact,
    barrier_summary_report,
    compute_barrier_impacts,
    compute_barrier_strength,
    create_barrier_properties,
    extract_separatrices,
    map_barriers_to_geography,
    rank_barriers,
)
from poverty_tda.analysis.critical_points import (
    KNOWN_AFFLUENT_LADS,
    KNOWN_DEPRIVED_LADS,
    CriticalPointClassification,
    LADSummary,
    ValidationResult,
    ValidationSummary,
    aggregate_by_lad,
    classify_critical_points,
    compute_imd_overlap,
    generate_validation_report,
    get_points_by_classification,
    get_points_in_lad,
    get_severity_ranking,
    map_to_lsoa,
    to_dataframe,
    to_geodataframe,
    validate_against_known_patterns,
)
from poverty_tda.analysis.pathways import (
    GatewayLSOA,
    IntegralLine,
    compute_gateway_impacts,
    compute_gradient_field,
    compute_lsoa_flow_paths,
    gateway_summary_report,
    identify_gateway_lsoas,
    rank_gateway_lsoas,
    score_gateway_impact,
    trace_integral_line,
)
from poverty_tda.analysis.trap_identification import (
    BasinProperties,
    TrapScore,
    compute_trap_score,
    estimate_basin_population,
    extract_basin_properties,
    rank_poverty_traps,
    trap_summary_report,
)

__all__ = [
    "CriticalPointClassification",
    "LADSummary",
    "ValidationResult",
    "ValidationSummary",
    "KNOWN_DEPRIVED_LADS",
    "KNOWN_AFFLUENT_LADS",
    "classify_critical_points",
    "map_to_lsoa",
    "aggregate_by_lad",
    "get_points_by_classification",
    "get_points_in_lad",
    "get_severity_ranking",
    "to_dataframe",
    "to_geodataframe",
    "validate_against_known_patterns",
    "generate_validation_report",
    "compute_imd_overlap",
    "BasinProperties",
    "TrapScore",
    "extract_basin_properties",
    "compute_trap_score",
    "estimate_basin_population",
    "rank_poverty_traps",
    "trap_summary_report",
    "BarrierProperties",
    "BarrierImpact",
    "extract_separatrices",
    "compute_barrier_strength",
    "create_barrier_properties",
    "map_barriers_to_geography",
    "rank_barriers",
    "analyze_barrier_impact",
    "compute_barrier_impacts",
    "barrier_summary_report",
    "IntegralLine",
    "GatewayLSOA",
    "compute_gradient_field",
    "trace_integral_line",
    "compute_lsoa_flow_paths",
    "identify_gateway_lsoas",
    "score_gateway_impact",
    "compute_gateway_impacts",
    "rank_gateway_lsoas",
    "gateway_summary_report",
]
